name: C/C++ CI

# mv build/Release/SDL2.dll ./

# libstdc++-6.dll
#           libwinpthread-1.dll
#           libavif-16.dll
#           libpng16-16.dll
#           libtiff-6.dll
#           libtiffxx-6.dll
#           libwebp-7.dll
#           libsharpyuv-0.dll
#           libwebpdecoder-3.dll
#           libwebpmux-3.dll
#           libwebpdemux-2.dll
#           libjpeg-8.dll
#           libturbojpeg.dll
#           libjxl.dll
#           libjxl_cms.dll
#           libjxl_extras_codec.dll
#           libjxl_threads.dll

# cp "${MINGW_PREFIX}/bin/libstdc++-6.dll" ./
#         cp "${MINGW_PREFIX}/bin/libwinpthread-1.dll" ./
#         cp "${MINGW_PREFIX}/bin/libavif-16.dll" ./
#         cp "${MINGW_PREFIX}/bin/libpng16-16.dll" ./
#         cp "${MINGW_PREFIX}/bin/libtiff-6.dll" ./
#         cp "${MINGW_PREFIX}/bin/libtiffxx-6.dll" ./
#         cp "${MINGW_PREFIX}/bin/libwebp-7.dll" ./
#         cp "${MINGW_PREFIX}/bin/libsharpyuv-0.dll" ./
#         cp "${MINGW_PREFIX}/bin/libwebpdecoder-3.dll" ./
#         cp "${MINGW_PREFIX}/bin/libwebpmux-3.dll" ./
#         cp "${MINGW_PREFIX}/bin/libwebpdemux-2.dll" ./
#         cp "${MINGW_PREFIX}/bin/libjpeg-8.dll" ./
#         cp "${MINGW_PREFIX}/bin/libturbojpeg.dll" ./
#         cp "${MINGW_PREFIX}/bin/libjxl.dll" ./
#         cp "${MINGW_PREFIX}/bin/libjxl_cms.dll" ./
#         cp "${MINGW_PREFIX}/bin/libjxl_extras_codec.dll" ./
#         cp "${MINGW_PREFIX}/bin/libjxl_threads.dll" ./

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-mingw64:
    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ucrt64
        install: >-
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-SDL2
          mingw-w64-ucrt-x86_64-SDL2_image
          make
          zip
    - name: Test SDL installation
      run: |
        pkg-config sdl2 --cflags
        pkg-config sdl2 --libs
        pkg-config SDL2_image --cflags
        pkg-config SDL2_image --libs
    - name: Generate Build Configuration (Premake)
      run: ./create-makefile-windows.bat
    - name: Build Tool (make)
      run: make config=release
    - name: Zip files into artifact
      run: |
        mv build/Release/ez-stream-tool ./
        echo "${MINGW_PREFIX}/bin/SDL2.dll"
        cp "${MINGW_PREFIX}/bin/SDL2.dll" ./
        cp "${MINGW_PREFIX}/bin/SDL2_image.dll" ./
        cp "${MINGW_PREFIX}/bin/libgcc_s_seh-1.dll" ./
    - name: Add artifact to Actions run
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: |
          ez-stream-tool.exe
          SDL2.dll
          SDL2_image.dll
          libgcc_s_seh-1.dll
          overlay.html
          res

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Dependencies
      run: |
        sudo apt-get install build-essential libsdl2-dev libsdl2-image-dev
    - name: Test SDL installation
      run: |
        sdl2-config --cflags
    - name: Generate Build Configuration (Premake)
      run: ./create-makefile-unix.sh
    - name: Build Tool (make)
      run: make config=release
    - name: Zip files into artifact
      run: |
        mv build/Release/ez-stream-tool ./
    - name: Add artifact to Actions run
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: |
          ez-stream-tool
          overlay.html
          res
