name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-mingw64:
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Generate Build Configuration (Premake)
      run: ./create-makefile-windows.bat
    - name: Build SDL2 and Tool (make)
      run: make config=release
    - name: Zip files into artifact
      run: |
        mv build/Release/ez-stream-tool ./
        mv build/Release/SDL2.dll ./
        zip -r build.zip ez-stream-tool.exe SDL2.dll overlay.html res
    - name: Add artifact to Actions run
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: build.zip

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Generate Build Configuration (Premake)
      run: ./create-makefile-unix.sh
    - name: Build SDL2 and Tool (make)
      run: make config=release
    - name: Zip files into artifact
      run: |
        mv build/Release/ez-stream-tool ./
        zip -r build.zip ez-stream-tool overlay.html res
    - name: Add artifact to Actions run
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: build.zip
