name: C/C++ CI

# mv build/Release/SDL2.dll ./

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-mingw64:
    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw64
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-SDL2
          make
    - name: Test SDL installation
      run: |
        pkg-config sdl2 --cflags
    - name: Generate Build Configuration (Premake)
      run: ./create-makefile-windows.bat
    - name: Build Tool (make)
      run: make config=release
    - name: Zip files into artifact
      run: |
        mv build/Release/ez-stream-tool ./
        zip -r build.zip ez-stream-tool.exe SDL2.dll overlay.html res
    - name: Add artifact to Actions run
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: build.zip

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Dependencies
      run: |
        sudo apt-get install build-essential libsdl2-dev
    - name: Test SDL installation
      run: |
        sdl2-config --cflags
    - name: Generate Build Configuration (Premake)
      run: ./create-makefile-unix.sh
    - name: Build Tool (make)
      run: make config=release
    - name: Zip files into artifact
      run: |
        mv build/Release/ez-stream-tool ./
        zip -r build.zip ez-stream-tool overlay.html res
    - name: Add artifact to Actions run
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: build.zip
